import { createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { tcpChecksum, writeInternetChecksum } from './checksum.ts';

const FRAME_LENGTH = 54;
const RECORD_LENGTH = 16 + FRAME_LENGTH;
const OUTPUT_PATH = resolve(import.meta.dirname, '../generated/tcp-handshake.pcap');
const MANIFEST_PATH = resolve(import.meta.dirname, '../manifests/tcp-handshake.json');

function writeUint16(
  bytes: Uint8Array,
  offset: number,
  value: number,
  littleEndian: boolean,
): void {
  if (littleEndian) {
    bytes[offset] = value & 0xff;
    bytes[offset + 1] = value >>> 8;
  } else {
    bytes[offset] = value >>> 8;
    bytes[offset + 1] = value & 0xff;
  }
}

function writeUint32(
  bytes: Uint8Array,
  offset: number,
  value: number,
  littleEndian: boolean,
): void {
  if (littleEndian) {
    bytes[offset] = value & 0xff;
    bytes[offset + 1] = (value >>> 8) & 0xff;
    bytes[offset + 2] = (value >>> 16) & 0xff;
    bytes[offset + 3] = (value >>> 24) & 0xff;
  } else {
    bytes[offset] = (value >>> 24) & 0xff;
    bytes[offset + 1] = (value >>> 16) & 0xff;
    bytes[offset + 2] = (value >>> 8) & 0xff;
    bytes[offset + 3] = value & 0xff;
  }
}

function writeIpv4(
  bytes: Uint8Array,
  offset: number,
  address: readonly [number, number, number, number],
): void {
  bytes.set(address, offset);
}

function buildFrame(index: number): Uint8Array {
  const frame = new Uint8Array(FRAME_LENGTH);
  const clientMac = [0x02, 0x00, 0x00, 0x00, 0x00, 0x01];
  const serverMac = [0x02, 0x00, 0x00, 0x00, 0x00, 0x02];
  const clientIp: [number, number, number, number] = [192, 0, 2, 10];
  const serverIp: [number, number, number, number] = [198, 51, 100, 20];
  const clientToServer = index !== 1;
  frame.set(clientToServer ? serverMac : clientMac, 0);
  frame.set(clientToServer ? clientMac : serverMac, 6);
  frame.set([0x08, 0x00], 12);

  const ipOffset = 14;
  frame[ipOffset] = 0x45;
  writeUint16(frame, ipOffset + 2, 40, false);
  writeUint16(frame, ipOffset + 4, index + 1, false);
  writeUint16(frame, ipOffset + 6, 0x4000, false);
  frame[ipOffset + 8] = 64;
  frame[ipOffset + 9] = 6;
  writeIpv4(frame, ipOffset + 12, clientToServer ? clientIp : serverIp);
  writeIpv4(frame, ipOffset + 16, clientToServer ? serverIp : clientIp);
  writeInternetChecksum(frame, ipOffset + 10, ipOffset, 20);

  const tcpOffset = 34;
  writeUint16(frame, tcpOffset, clientToServer ? 51515 : 443, false);
  writeUint16(frame, tcpOffset + 2, clientToServer ? 443 : 51515, false);
  writeUint32(frame, tcpOffset + 4, clientToServer ? (index === 2 ? 1001 : 1000) : 5000, false);
  writeUint32(frame, tcpOffset + 8, index === 0 ? 0 : clientToServer ? 5001 : 1001, false);
  frame[tcpOffset + 12] = 0x50;
  frame[tcpOffset + 13] = index === 0 ? 0x02 : index === 1 ? 0x12 : 0x10;
  writeUint16(frame, tcpOffset + 14, 65535, false);
  writeUint16(frame, tcpOffset + 20, 0, false);
  writeUint16(frame, tcpOffset + 22, 0, false);
  const checksum = tcpChecksum(frame, ipOffset, tcpOffset, 20);
  writeUint16(frame, tcpOffset + 16, checksum, false);
  return frame;
}

export function buildTcpHandshakePcap(): Uint8Array {
  const bytes = new Uint8Array(24 + 3 * RECORD_LENGTH);
  bytes.set([0xd4, 0xc3, 0xb2, 0xa1], 0);
  writeUint16(bytes, 4, 2, true);
  writeUint16(bytes, 6, 4, true);
  writeUint32(bytes, 8, 0, true);
  writeUint32(bytes, 12, 0, true);
  writeUint32(bytes, 16, 65535, true);
  writeUint32(bytes, 20, 1, true);
  for (let index = 0; index < 3; index += 1) {
    const recordOffset = 24 + index * RECORD_LENGTH;
    writeUint32(bytes, recordOffset, 1, true);
    writeUint32(bytes, recordOffset + 4, index * 10000, true);
    writeUint32(bytes, recordOffset + 8, FRAME_LENGTH, true);
    writeUint32(bytes, recordOffset + 12, FRAME_LENGTH, true);
    bytes.set(buildFrame(index), recordOffset + 16);
  }
  return bytes;
}

export async function writeTcpHandshakeFixture(): Promise<void> {
  const bytes = buildTcpHandshakePcap();
  const sha256 = createHash('sha256').update(bytes).digest('hex');
  await mkdir(dirname(OUTPUT_PATH), { recursive: true });
  await mkdir(dirname(MANIFEST_PATH), { recursive: true });
  await writeFile(OUTPUT_PATH, bytes);
  await writeFile(
    MANIFEST_PATH,
    `${JSON.stringify(
      {
        name: 'tcp-handshake',
        file: 'generated/tcp-handshake.pcap',
        sha256,
        byteLength: bytes.byteLength,
        license:
          'Original synthetic traffic generated by WireLens; no real network traffic or captured user data.',
        packets: [
          { number: 1, timestampNs: '1000000000', flags: 'SYN', sequence: 1000, acknowledgment: 0 },
          {
            number: 2,
            timestampNs: '1010000000',
            flags: 'SYN + ACK',
            sequence: 5000,
            acknowledgment: 1001,
          },
          {
            number: 3,
            timestampNs: '1020000000',
            flags: 'ACK',
            sequence: 1001,
            acknowledgment: 5001,
          },
        ],
      },
      null,
      2,
    )}\n`,
  );
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  await writeTcpHandshakeFixture();
}
