import { createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { format } from 'prettier';
import { buildTcpHandshakePcap } from './build-handshake.ts';
import { tcpChecksum, writeInternetChecksum } from './checksum.ts';

const generated = resolve(import.meta.dirname, '../generated');
const manifests = resolve(import.meta.dirname, '../manifests');
const license =
  'Original synthetic traffic generated by WireLens; no real network traffic or captured user data.';

async function manifestJson(
  name: string,
  file: string,
  bytes: Uint8Array,
  packets: number[],
  expectedFacts?: Record<string, unknown>,
): Promise<string> {
  return format(
    JSON.stringify({
      name,
      file: `generated/${file}`,
      sha256: createHash('sha256').update(bytes).digest('hex'),
      byteLength: bytes.byteLength,
      license,
      ...(expectedFacts ? { expectedFacts } : {}),
      packets,
    }),
    { parser: 'json', printWidth: 100, tabWidth: 2, useTabs: false },
  );
}

const u16 = (b: Uint8Array, o: number, v: number, le: boolean) => {
  b[o] = le ? v & 255 : v >>> 8;
  b[o + 1] = le ? v >>> 8 : v & 255;
};
const u32 = (b: Uint8Array, o: number, v: number, le: boolean) => {
  b[o] = le ? v & 255 : v >>> 24;
  b[o + 1] = le ? (v >>> 8) & 255 : (v >>> 16) & 255;
  b[o + 2] = le ? (v >>> 16) & 255 : (v >>> 8) & 255;
  b[o + 3] = le ? (v >>> 24) & 255 : v & 255;
};
async function save(
  name: string,
  bytes: Uint8Array,
  packets: number[] = [1, 2, 3],
  expectedFacts?: Record<string, unknown>,
): Promise<void> {
  const file = `${name}.pcap`;
  await writeFile(resolve(generated, file), bytes);
  await writeFile(
    resolve(manifests, `${name}.json`),
    await manifestJson(name, file, bytes, packets, expectedFacts),
  );
}
async function savePcapng(name: string, bytes: Uint8Array, packets: number[]): Promise<void> {
  const file = `${name}.pcapng`;
  await writeFile(resolve(generated, file), bytes);
  await writeFile(
    resolve(manifests, `${name}.json`),
    await manifestJson(name, file, bytes, packets),
  );
}
function classicVariant(little: boolean, nanoseconds: boolean): Uint8Array {
  const source = buildTcpHandshakePcap();
  const result = new Uint8Array(source);
  result.set(
    little
      ? nanoseconds
        ? [0x4d, 0x3c, 0xb2, 0xa1]
        : [0xd4, 0xc3, 0xb2, 0xa1]
      : nanoseconds
        ? [0xa1, 0xb2, 0x3c, 0x4d]
        : [0xa1, 0xb2, 0xc3, 0xd4],
    0,
  );
  u16(result, 4, 2, little);
  u16(result, 6, 4, little);
  u32(result, 8, 0, little);
  u32(result, 12, 0, little);
  u32(result, 16, 65535, little);
  u32(result, 20, 1, little);
  for (let i = 0; i < 3; i += 1) {
    const o = 24 + i * 70;
    u32(result, o, 1, little);
    u32(result, o + 4, i * 10000, little);
    u32(result, o + 8, 54, little);
    u32(result, o + 12, 54, little);
  }
  return result;
}
function pcapng(): Uint8Array {
  const source = buildTcpHandshakePcap();
  const result = new Uint8Array(28 + 20 + 3 * 88);
  const putBlock = (o: number, type: number, length: number) => {
    u32(result, o, type, true);
    u32(result, o + 4, length, true);
    u32(result, o + length - 4, length, true);
  };
  putBlock(0, 0x0a0d0d0a, 28);
  result.set([0x4d, 0x3c, 0x2b, 0x1a], 8);
  result[12] = 1;
  putBlock(28, 1, 20);
  u16(result, 36, 1, true);
  u32(result, 40, 65535, true);
  for (let i = 0; i < 3; i += 1) {
    const o = 48 + i * 88;
    putBlock(o, 6, 88);
    u32(result, o + 8, 0, true);
    u32(result, o + 12, 0, true);
    u32(result, o + 16, 1000000 + i * 10000, true);
    u32(result, o + 20, 54, true);
    u32(result, o + 24, 54, true);
    result.set(source.slice(40 + i * 70, 40 + i * 70 + 54), o + 28);
  }
  return result;
}
function ipv6UdpPcapng(): Uint8Array {
  const frameLength = 62;
  const result = new Uint8Array(28 + 20 + 96);
  const putBlock = (o: number, type: number, length: number) => {
    u32(result, o, type, true);
    u32(result, o + 4, length, true);
    u32(result, o + length - 4, length, true);
  };
  putBlock(0, 0x0a0d0d0a, 28);
  result.set([0x4d, 0x3c, 0x2b, 0x1a], 8);
  result[12] = 1;
  putBlock(28, 1, 20);
  u16(result, 36, 1, true);
  u32(result, 40, 65535, true);
  putBlock(48, 6, 96);
  u32(result, 56, 0, true);
  u32(result, 60, 0, true);
  u32(result, 64, 1000000, true);
  u32(result, 68, frameLength, true);
  u32(result, 72, frameLength, true);
  const frame = 76;
  result.set([0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0x86, 0xdd], frame);
  result[frame + 14] = 0x60;
  result[frame + 18] = 0;
  result[frame + 19] = 8;
  result[frame + 20] = 17;
  result[frame + 21] = 64;
  result.set([0x20, 0x01, 0x0d, 0xb8], frame + 22);
  result[frame + 37] = 1;
  result.set([0x20, 0x01, 0x0d, 0xb8], frame + 38);
  result[frame + 53] = 2;
  u16(result, frame + 54, 53000, false);
  u16(result, frame + 56, 53, false);
  u16(result, frame + 58, 8, false);
  return result;
}

function dnsName(): number[] {
  return [7, ...Array.from('example').map((value) => value.charCodeAt(0)), 3, 99, 111, 109, 0];
}

function dnsMessage(
  response: boolean,
  id: number,
  responseCode: number,
  answerType: number,
): Uint8Array {
  const name = dnsName();
  const answerLength = answerType === 1 ? 4 : answerType === 28 ? 16 : 0;
  const result = new Uint8Array(
    12 + name.length + 4 + (response && answerType ? 12 + answerLength : 0),
  );
  u16(result, 0, id, false);
  u16(result, 2, (response ? 0x8000 : 0) | responseCode, false);
  u16(result, 4, 1, false);
  u16(result, 6, response && answerType ? 1 : 0, false);
  result.set(name, 12);
  u16(result, 12 + name.length, answerType || 1, false);
  u16(result, 14 + name.length, 1, false);
  if (response && answerType) {
    const answer = 16 + name.length;
    result[answer] = 0xc0;
    result[answer + 1] = 0x0c;
    u16(result, answer + 2, answerType, false);
    u16(result, answer + 4, 1, false);
    u32(result, answer + 6, 60, false);
    u16(result, answer + 10, answerLength, false);
    if (answerType === 1) result.set([192, 0, 2, 53], answer + 12);
    else result.set([0x20, 0x01, 0x0d, 0xb8, ...new Array(11).fill(0), 0x35], answer + 12);
  }
  return result;
}

function dnsPcap(): Uint8Array {
  const latencies = [10_000, 20_000, 30_000, 40_000, 500_000, 60_000, 70_000];
  const responseCodes = [0, 0, 0, 0, 0, 3, 2];
  const answerTypes = [1, 28, 1, 1, 1, 0, 0];
  const messages: Uint8Array[] = [];
  for (let index = 0; index < latencies.length; index += 1) {
    const id = 0x4000 + index;
    messages.push(dnsMessage(false, id, 0, answerTypes[index]));
    messages.push(dnsMessage(true, id, responseCodes[index], answerTypes[index]));
  }
  const frameLength = (message: Uint8Array) => 14 + 20 + 8 + message.length;
  const total = 24 + messages.reduce((sum, message) => sum + 16 + frameLength(message), 0);
  const result = new Uint8Array(total);
  result.set([0xd4, 0xc3, 0xb2, 0xa1], 0);
  u16(result, 4, 2, true);
  u16(result, 6, 4, true);
  u32(result, 16, 65_535, true);
  u32(result, 20, 1, true);
  let record = 24;
  for (let index = 0; index < messages.length; index += 1) {
    const message = messages[index];
    const pair = Math.floor(index / 2);
    const response = index % 2 === 1;
    const frame = record + 16;
    const frameBytes = frameLength(message);
    u32(result, record, pair + 1, true);
    u32(result, record + 4, response ? latencies[pair] : 0, true);
    u32(result, record + 8, frameBytes, true);
    u32(result, record + 12, frameBytes, true);
    result.set(
      response ? [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2] : [0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1],
      frame,
    );
    result.set([0x08, 0x00], frame + 12);
    const ip = frame + 14;
    result[ip] = 0x45;
    u16(result, ip + 2, 20 + 8 + message.length, false);
    result[ip + 8] = 64;
    result[ip + 9] = 17;
    result.set(
      response ? [198, 51, 100, 53, 192, 0, 2, 10] : [192, 0, 2, 10, 198, 51, 100, 53],
      ip + 12,
    );
    const udp = ip + 20;
    u16(result, udp, response ? 53 : 53_000, false);
    u16(result, udp + 2, response ? 53_000 : 53, false);
    u16(result, udp + 4, 8 + message.length, false);
    result.set(message, udp + 8);
    record += 16 + frameBytes;
  }
  return result;
}

interface TcpPacket {
  clientToServer: boolean;
  sequence: number;
  acknowledgment: number;
  flags: number;
  payload?: string | Uint8Array;
}

interface TcpPcapOptions {
  clientPort?: number;
  serverPort?: number;
}

function tcpPcap(packets: TcpPacket[], options: TcpPcapOptions = {}): Uint8Array {
  const encoder = new TextEncoder();
  const payloads = packets.map((packet) =>
    typeof packet.payload === 'string'
      ? encoder.encode(packet.payload)
      : (packet.payload ?? new Uint8Array()),
  );
  const clientPort = options.clientPort ?? 51_515;
  const serverPort = options.serverPort ?? 443;
  const frameLength = (index: number) => 14 + 20 + 20 + payloads[index].byteLength;
  const total = 24 + packets.reduce((sum, _packet, index) => sum + 16 + frameLength(index), 0);
  const result = new Uint8Array(total);
  result.set([0xd4, 0xc3, 0xb2, 0xa1], 0);
  u16(result, 4, 2, true);
  u16(result, 6, 4, true);
  u32(result, 16, 65_535, true);
  u32(result, 20, 1, true);
  let record = 24;
  for (let index = 0; index < packets.length; index += 1) {
    const packet = packets[index];
    const payload = payloads[index];
    const length = frameLength(index);
    u32(result, record, 1, true);
    u32(result, record + 4, index * 10_000, true);
    u32(result, record + 8, length, true);
    u32(result, record + 12, length, true);
    const frame = record + 16;
    result.set(
      packet.clientToServer
        ? [2, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 1]
        : [2, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 2],
      frame,
    );
    result.set([0x08, 0x00], frame + 12);
    const ip = frame + 14;
    result[ip] = 0x45;
    u16(result, ip + 2, 20 + 20 + payload.byteLength, false);
    u16(result, ip + 4, index + 1, false);
    u16(result, ip + 6, 0x4000, false);
    result[ip + 8] = 64;
    result[ip + 9] = 6;
    result.set(
      packet.clientToServer ? [192, 0, 2, 10, 198, 51, 100, 20] : [198, 51, 100, 20, 192, 0, 2, 10],
      ip + 12,
    );
    writeInternetChecksum(result, ip + 10, ip, 20);
    const tcp = ip + 20;
    u16(result, tcp, packet.clientToServer ? clientPort : serverPort, false);
    u16(result, tcp + 2, packet.clientToServer ? serverPort : clientPort, false);
    u32(result, tcp + 4, packet.sequence, false);
    u32(result, tcp + 8, packet.acknowledgment, false);
    result[tcp + 12] = 0x50;
    result[tcp + 13] = packet.flags;
    u16(result, tcp + 14, 65_535, false);
    result.set(payload, tcp + 20);
    u16(result, tcp + 16, tcpChecksum(result, ip, tcp, 20 + payload.byteLength), false);
    record += 16 + length;
  }
  return result;
}

const tcpReset = tcpPcap([
  { clientToServer: true, sequence: 1000, acknowledgment: 0, flags: 0x02 },
  { clientToServer: false, sequence: 5000, acknowledgment: 1001, flags: 0x12 },
  { clientToServer: true, sequence: 1001, acknowledgment: 5001, flags: 0x10 },
  { clientToServer: false, sequence: 5001, acknowledgment: 1001, flags: 0x14 },
]);

const tcpRetransmission = tcpPcap([
  { clientToServer: true, sequence: 1000, acknowledgment: 0, flags: 0x02 },
  { clientToServer: false, sequence: 5000, acknowledgment: 1001, flags: 0x12 },
  { clientToServer: true, sequence: 1001, acknowledgment: 5001, flags: 0x10 },
  { clientToServer: true, sequence: 1001, acknowledgment: 5001, flags: 0x10, payload: 'hello' },
  { clientToServer: true, sequence: 1001, acknowledgment: 5001, flags: 0x10, payload: 'hello' },
  { clientToServer: true, sequence: 1006, acknowledgment: 5001, flags: 0x11 },
  { clientToServer: false, sequence: 5001, acknowledgment: 1007, flags: 0x11 },
]);

export const HTTP_HEADER_SENTINEL = 'wirelens-http-header-secret-29';
export const HTTP_BODY_SENTINEL = 'wirelens-http-body-secret-29';

const httpBody = `{"value":"${HTTP_BODY_SENTINEL}"}`;
const httpRequestParts = [
  `POST /search?term=private&sort=recent HTTP/1.1\r\nHost: example.test\r\nAuthorization: Bearer ${HTTP_HEADER_SENTINEL}\r\n`,
  `Cookie: session=${HTTP_HEADER_SENTINEL}\r\nX-Api-Key: ${HTTP_HEADER_SENTINEL}\r\nContent-Type: application/json\r\nContent-Length: ${httpBody.length}\r\n\r\n`,
  httpBody,
];
const httpRequestByteLength = httpRequestParts.reduce(
  (length, part) => length + new TextEncoder().encode(part).byteLength,
  0,
);
const httpResponse =
  'HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: 11\r\nServer: wirelens-test\r\nDate: Thu, 01 Jan 1970 00:00:00 GMT\r\n\r\n{"ok":true}';

export function buildPlaintextHttpPcap(): Uint8Array {
  let clientSequence = 1001;
  const requestPackets: TcpPacket[] = httpRequestParts.map((payload) => {
    const packet = {
      clientToServer: true,
      sequence: clientSequence,
      acknowledgment: 5001,
      flags: 0x10,
      payload,
    };
    clientSequence += new TextEncoder().encode(payload).byteLength;
    return packet;
  });
  return tcpPcap(
    [
      { clientToServer: true, sequence: 1000, acknowledgment: 0, flags: 0x02 },
      { clientToServer: false, sequence: 5000, acknowledgment: 1001, flags: 0x12 },
      { clientToServer: true, sequence: 1001, acknowledgment: 5001, flags: 0x10 },
      ...requestPackets,
      {
        clientToServer: false,
        sequence: 5001,
        acknowledgment: 1001 + httpRequestByteLength,
        flags: 0x10,
        payload: httpResponse,
      },
    ],
    { serverPort: 80 },
  );
}

function concatBytes(...parts: Uint8Array[]): Uint8Array {
  const result = new Uint8Array(parts.reduce((length, part) => length + part.byteLength, 0));
  let offset = 0;
  for (const part of parts) {
    result.set(part, offset);
    offset += part.byteLength;
  }
  return result;
}

function tlsExtension(type: number, data: Uint8Array): Uint8Array {
  const result = new Uint8Array(4 + data.byteLength);
  u16(result, 0, type, false);
  u16(result, 2, data.byteLength, false);
  result.set(data, 4);
  return result;
}

function tlsHandshakeRecord(
  handshakeType: number,
  body: Uint8Array,
  recordVersion: readonly [number, number],
): Uint8Array {
  const handshake = new Uint8Array(4 + body.byteLength);
  handshake[0] = handshakeType;
  handshake[1] = (body.byteLength >>> 16) & 0xff;
  handshake[2] = (body.byteLength >>> 8) & 0xff;
  handshake[3] = body.byteLength & 0xff;
  handshake.set(body, 4);
  const record = new Uint8Array(5 + handshake.byteLength);
  record[0] = 0x16;
  record.set(recordVersion, 1);
  u16(record, 3, handshake.byteLength, false);
  record.set(handshake, 5);
  return record;
}

function buildTlsClientHello(): Uint8Array {
  const encoder = new TextEncoder();
  const serverName = encoder.encode('example.test');
  const serverNameData = new Uint8Array(2 + 1 + 2 + serverName.byteLength);
  u16(serverNameData, 0, 1 + 2 + serverName.byteLength, false);
  serverNameData[2] = 0;
  u16(serverNameData, 3, serverName.byteLength, false);
  serverNameData.set(serverName, 5);
  const supportedVersionsData = new Uint8Array([4, 3, 4, 3, 3]);
  const extensions = concatBytes(
    tlsExtension(0, serverNameData),
    tlsExtension(43, supportedVersionsData),
  );
  const body = new Uint8Array(43 + extensions.byteLength);
  u16(body, 0, 0x0303, false);
  body.set(
    Uint8Array.from({ length: 32 }, (_, index) => index + 1),
    2,
  );
  body[34] = 0;
  u16(body, 35, 2, false);
  u16(body, 37, 0x1301, false);
  body[39] = 1;
  body[40] = 0;
  u16(body, 41, extensions.byteLength, false);
  body.set(extensions, 43);
  return tlsHandshakeRecord(1, body, [0x03, 0x01]);
}

function buildTlsServerHello(): Uint8Array {
  const supportedVersion = new Uint8Array([0x03, 0x04]);
  const extensions = tlsExtension(43, supportedVersion);
  const body = new Uint8Array(40 + extensions.byteLength);
  u16(body, 0, 0x0303, false);
  body.set(
    Uint8Array.from({ length: 32 }, (_, index) => index + 0x21),
    2,
  );
  body[34] = 0;
  u16(body, 35, 0x1301, false);
  body[37] = 0;
  u16(body, 38, extensions.byteLength, false);
  body.set(extensions, 40);
  return tlsHandshakeRecord(2, body, [0x03, 0x03]);
}

export function buildTlsHandshakePcap(): Uint8Array {
  return tcpPcap(
    [
      { clientToServer: true, sequence: 1000, acknowledgment: 0, flags: 0x02 },
      { clientToServer: false, sequence: 5000, acknowledgment: 1001, flags: 0x12 },
      { clientToServer: true, sequence: 1001, acknowledgment: 5001, flags: 0x10 },
      {
        clientToServer: true,
        sequence: 1001,
        acknowledgment: 5001,
        flags: 0x10,
        payload: buildTlsClientHello(),
      },
      {
        clientToServer: false,
        sequence: 5001,
        acknowledgment: 1001 + buildTlsClientHello().byteLength,
        flags: 0x10,
        payload: buildTlsServerHello(),
      },
    ],
    { serverPort: 443 },
  );
}

await mkdir(generated, { recursive: true });
await mkdir(manifests, { recursive: true });
await save('tcp-handshake-big-endian', classicVariant(false, false));
await save('tcp-handshake-nanoseconds', classicVariant(true, true));
await writeFile(resolve(generated, 'tcp-handshake.pcapng'), pcapng());
await writeFile(
  resolve(manifests, 'tcp-handshake-pcapng.json'),
  await manifestJson('tcp-handshake-pcapng', 'tcp-handshake.pcapng', pcapng(), [1, 2, 3]),
);
await writeFile(resolve(generated, 'tcp-reset.pcap'), tcpReset);
await writeFile(
  resolve(manifests, 'tcp-reset.json'),
  await manifestJson('tcp-reset', 'tcp-reset.pcap', tcpReset, [1, 2, 3, 4], {
    handshake: 'complete',
    termination: 'reset',
    observationTypes: ['tcp-reset'],
  }),
);
await writeFile(resolve(generated, 'tcp-retransmission.pcap'), tcpRetransmission);
await writeFile(
  resolve(manifests, 'tcp-retransmission.json'),
  await manifestJson(
    'tcp-retransmission',
    'tcp-retransmission.pcap',
    tcpRetransmission,
    [1, 2, 3, 4, 5, 6, 7],
    {
      handshake: 'complete',
      termination: 'graceful',
      observationTypes: ['tcp-retransmission-candidate'],
      retransmissionEvidence: [4, 5],
    },
  ),
);
await savePcapng('ipv6-udp', ipv6UdpPcapng(), [1]);
await writeFile(resolve(generated, 'dns-exchanges.pcap'), dnsPcap());
await writeFile(
  resolve(manifests, 'dns-exchanges.json'),
  await manifestJson(
    'dns-exchanges',
    'dns-exchanges.pcap',
    dnsPcap(),
    Array.from({ length: 14 }, (_, i) => i + 1),
  ),
);
await save('plaintext-http', buildPlaintextHttpPcap(), [1, 2, 3, 4, 5, 6, 7], {
  handshake: 'complete',
  requestPacketNumbers: [4, 5, 6],
  responsePacketNumbers: [7],
  matched: true,
  queryValues: 'redacted',
  redactedHeaders: ['authorization', 'cookie', 'x-api-key'],
  body: 'not-retained',
});
await save('tls-handshake', buildTlsHandshakePcap(), [1, 2, 3, 4, 5], {
  handshake: 'complete',
  clientHelloPacketNumbers: [4],
  serverHelloPacketNumbers: [5],
  serverName: 'example.test',
  offeredVersions: ['TLS 1.3', 'TLS 1.2'],
  negotiatedVersion: 'TLS 1.3',
});
