import { createHash } from 'node:crypto';
import { readdirSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { format } from 'prettier';
import { buildTcpHandshakePcap } from './build-handshake.js';

describe('buildTcpHandshakePcap', () => {
  it('builds the exact three-packet handshake capture', () => {
    const bytes = buildTcpHandshakePcap();
    expect(bytes.byteLength).toBe(234);
    expect([...bytes.slice(0, 4)]).toEqual([0xd4, 0xc3, 0xb2, 0xa1]);

    const littleEndian = (offset: number) => new DataView(bytes.buffer).getUint32(offset, true);
    const network16 = (frameOffset: number, offset: number) =>
      new DataView(bytes.buffer).getUint16(frameOffset + offset, false);
    const network32 = (frameOffset: number, offset: number) =>
      new DataView(bytes.buffer).getUint32(frameOffset + offset, false);
    const frameOffsets = [24 + 16, 24 + 16 + 70, 24 + 16 + 140];
    expect(frameOffsets.map((offset) => littleEndian(offset - 16 + 8))).toEqual([54, 54, 54]);
    expect(frameOffsets.map((offset) => littleEndian(offset - 16 + 12))).toEqual([54, 54, 54]);
    expect(frameOffsets.map((offset) => littleEndian(offset - 16))).toEqual([1, 1, 1]);
    expect(frameOffsets.map((offset) => littleEndian(offset - 16 + 4))).toEqual([0, 10000, 20000]);

    const expectedAddresses = [
      [
        [192, 0, 2, 10],
        [198, 51, 100, 20],
      ],
      [
        [198, 51, 100, 20],
        [192, 0, 2, 10],
      ],
      [
        [192, 0, 2, 10],
        [198, 51, 100, 20],
      ],
    ];
    expect(
      frameOffsets.map((offset, index) => [
        [...bytes.slice(offset + 14 + 12, offset + 14 + 16)],
        [...bytes.slice(offset + 14 + 16, offset + 14 + 20)],
      ]),
    ).toEqual(expectedAddresses);
    expect(frameOffsets.map((offset) => network16(offset, 34))).toEqual([51515, 443, 51515]);
    expect(frameOffsets.map((offset) => network16(offset, 36))).toEqual([443, 51515, 443]);
    expect(frameOffsets.map((offset) => network32(offset, 38))).toEqual([1000, 5000, 1001]);
    expect(frameOffsets.map((offset) => network32(offset, 42))).toEqual([0, 1001, 5001]);
    expect(frameOffsets.map((offset) => bytes[offset + 47])).toEqual([0x02, 0x12, 0x10]);
  });

  it('is deterministic across generations', () => {
    const hash = (bytes: Uint8Array) => createHash('sha256').update(bytes).digest('hex');
    expect(hash(buildTcpHandshakePcap())).toBe(hash(buildTcpHandshakePcap()));
  });

  it('matches the reviewed hash and checked-in bytes', () => {
    const generated = buildTcpHandshakePcap();
    const checkedIn = readFileSync(resolve(import.meta.dirname, '../generated/tcp-handshake.pcap'));
    expect(createHash('sha256').update(generated).digest('hex')).toBe(
      'a55e8e886b92357ffd09b5ee50ec29838b84b079c021fdf4f6869125e4995a82',
    );
    expect([...generated]).toEqual([...checkedIn]);
  });
});

describe('checked-in Phase 2 fixtures', () => {
  it('has deterministic formatted manifests, original-license text, and existing JSON goldens', async () => {
    const reviewedHashes: Record<string, string> = {
      'tcp-reset.pcap': '69bff7a7e9439b6f98258ad7474b8610029de457510a269f40b439adef2fe17b',
      'tcp-retransmission.pcap': '75ed3678a8de6db5e4d4a9e5046ebfc3edbf0eaa992706d2ab05428b1a4e9b24',
    };
    const generated = readdirSync(resolve(import.meta.dirname, '../generated'))
      .filter((name) => /\.(pcap|pcapng)$/u.test(name))
      .sort();
    expect(generated).toEqual([
      'dns-exchanges.pcap',
      'ipv6-udp.pcapng',
      'plaintext-http.pcap',
      'tcp-handshake-big-endian.pcap',
      'tcp-handshake-nanoseconds.pcap',
      'tcp-handshake.pcap',
      'tcp-handshake.pcapng',
      'tcp-reset.pcap',
      'tcp-retransmission.pcap',
      'tls-handshake.pcap',
    ]);
    for (const file of generated) {
      const bytes = readFileSync(resolve(import.meta.dirname, '../generated', file));
      const stem = file.replace(/\.pcap(?:ng)?$/u, '');
      const manifestName =
        file.endsWith('.pcapng') && stem === 'tcp-handshake' ? 'tcp-handshake-pcapng' : stem;
      const manifestText = readFileSync(
        resolve(import.meta.dirname, '../manifests', `${manifestName}.json`),
        'utf8',
      );
      const manifest = JSON.parse(manifestText) as {
        sha256: string;
        license: string;
        packets: unknown[];
      };
      expect(manifestText).toBe(
        await format(manifestText, {
          parser: 'json',
          printWidth: 100,
          tabWidth: 2,
          useTabs: false,
        }),
      );
      expect(manifest.sha256).toBe(createHash('sha256').update(bytes).digest('hex'));
      if (reviewedHashes[file]) expect(manifest.sha256).toBe(reviewedHashes[file]);
      expect(manifest.license).toMatch(/^Original synthetic traffic generated by WireLens/u);
      if (manifest.packets.every((packet) => typeof packet === 'number')) {
        expect(manifestText).toContain(`"packets": [${manifest.packets.join(', ')}]`);
      }
      if (!['plaintext-http.pcap', 'tls-handshake.pcap'].includes(file)) {
        expect(() =>
          JSON.parse(
            readFileSync(
              resolve(import.meta.dirname, '../expected', `${file}.capture.json`),
              'utf8',
            ),
          ),
        ).not.toThrow();
      }
    }
  });

  it('records the reviewed reset and retransmission facts', () => {
    const manifest = (name: string) =>
      JSON.parse(
        readFileSync(resolve(import.meta.dirname, '../manifests', `${name}.json`), 'utf8'),
      ) as { expectedFacts: Record<string, unknown> };
    expect(manifest('tcp-reset').expectedFacts).toEqual({
      handshake: 'complete',
      termination: 'reset',
      observationTypes: ['tcp-reset'],
    });
    expect(manifest('tcp-retransmission').expectedFacts).toEqual({
      handshake: 'complete',
      termination: 'graceful',
      observationTypes: ['tcp-retransmission-candidate'],
      retransmissionEvidence: [4, 5],
    });
  });
});
