import { createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { buildTcpHandshakePcap } from './build-handshake.ts';

const generated = resolve(import.meta.dirname, '../generated');
const manifests = resolve(import.meta.dirname, '../manifests');
const license =
  'Original synthetic traffic generated by WireLens; no real network traffic or captured user data.';

function manifestJson(name: string, file: string, bytes: Uint8Array, packets: number[]): string {
  const withoutPackets = JSON.stringify(
    {
      name,
      file: `generated/${file}`,
      sha256: createHash('sha256').update(bytes).digest('hex'),
      byteLength: bytes.byteLength,
      license,
    },
    null,
    2,
  );
  return `${withoutPackets.slice(0, -2)},\n  "packets": [${packets.join(', ')}]\n}\n`;
}

const u16 = (b: Uint8Array, o: number, v: number, le: boolean) => {
  b[o] = le ? v & 255 : v >>> 8;
  b[o + 1] = le ? v >>> 8 : v & 255;
};
const u32 = (b: Uint8Array, o: number, v: number, le: boolean) => {
  b[o] = le ? v & 255 : v >>> 24;
  b[o + 1] = le ? (v >>> 8) & 255 : (v >>> 16) & 255;
  b[o + 2] = le ? (v >>> 16) & 255 : (v >>> 8) & 255;
  b[o + 3] = le ? (v >>> 24) & 255 : v & 255;
};
async function save(name: string, bytes: Uint8Array): Promise<void> {
  const file = `${name}.pcap`;
  await writeFile(resolve(generated, file), bytes);
  await writeFile(resolve(manifests, `${name}.json`), manifestJson(name, file, bytes, [1, 2, 3]));
}
async function savePcapng(name: string, bytes: Uint8Array, packets: number[]): Promise<void> {
  const file = `${name}.pcapng`;
  await writeFile(resolve(generated, file), bytes);
  await writeFile(resolve(manifests, `${name}.json`), manifestJson(name, file, bytes, packets));
}
function classicVariant(little: boolean, nanoseconds: boolean): Uint8Array {
  const source = buildTcpHandshakePcap();
  const result = new Uint8Array(source);
  result.set(
    little
      ? nanoseconds
        ? [0x4d, 0x3c, 0xb2, 0xa1]
        : [0xd4, 0xc3, 0xb2, 0xa1]
      : nanoseconds
        ? [0xa1, 0xb2, 0x3c, 0x4d]
        : [0xa1, 0xb2, 0xc3, 0xd4],
    0,
  );
  u16(result, 4, 2, little);
  u16(result, 6, 4, little);
  u32(result, 8, 0, little);
  u32(result, 12, 0, little);
  u32(result, 16, 65535, little);
  u32(result, 20, 1, little);
  for (let i = 0; i < 3; i += 1) {
    const o = 24 + i * 70;
    u32(result, o, 1, little);
    u32(result, o + 4, i * 10000, little);
    u32(result, o + 8, 54, little);
    u32(result, o + 12, 54, little);
  }
  return result;
}
function pcapng(): Uint8Array {
  const source = buildTcpHandshakePcap();
  const result = new Uint8Array(28 + 20 + 3 * 88);
  const putBlock = (o: number, type: number, length: number) => {
    u32(result, o, type, true);
    u32(result, o + 4, length, true);
    u32(result, o + length - 4, length, true);
  };
  putBlock(0, 0x0a0d0d0a, 28);
  result.set([0x4d, 0x3c, 0x2b, 0x1a], 8);
  result[12] = 1;
  putBlock(28, 1, 20);
  u16(result, 36, 1, true);
  u32(result, 40, 65535, true);
  for (let i = 0; i < 3; i += 1) {
    const o = 48 + i * 88;
    putBlock(o, 6, 88);
    u32(result, o + 8, 0, true);
    u32(result, o + 12, 0, true);
    u32(result, o + 16, 1000000 + i * 10000, true);
    u32(result, o + 20, 54, true);
    u32(result, o + 24, 54, true);
    result.set(source.slice(40 + i * 70, 40 + i * 70 + 54), o + 28);
  }
  return result;
}
function ipv6UdpPcapng(): Uint8Array {
  const frameLength = 62;
  const result = new Uint8Array(28 + 20 + 96);
  const putBlock = (o: number, type: number, length: number) => {
    u32(result, o, type, true);
    u32(result, o + 4, length, true);
    u32(result, o + length - 4, length, true);
  };
  putBlock(0, 0x0a0d0d0a, 28);
  result.set([0x4d, 0x3c, 0x2b, 0x1a], 8);
  result[12] = 1;
  putBlock(28, 1, 20);
  u16(result, 36, 1, true);
  u32(result, 40, 65535, true);
  putBlock(48, 6, 96);
  u32(result, 56, 0, true);
  u32(result, 60, 0, true);
  u32(result, 64, 1000000, true);
  u32(result, 68, frameLength, true);
  u32(result, 72, frameLength, true);
  const frame = 76;
  result.set([0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0x86, 0xdd], frame);
  result[frame + 14] = 0x60;
  result[frame + 18] = 0;
  result[frame + 19] = 8;
  result[frame + 20] = 17;
  result[frame + 21] = 64;
  result.set([0x20, 0x01, 0x0d, 0xb8], frame + 22);
  result[frame + 37] = 1;
  result.set([0x20, 0x01, 0x0d, 0xb8], frame + 38);
  result[frame + 53] = 2;
  u16(result, frame + 54, 53000, false);
  u16(result, frame + 56, 53, false);
  u16(result, frame + 58, 8, false);
  return result;
}
await mkdir(generated, { recursive: true });
await mkdir(manifests, { recursive: true });
await save('tcp-handshake-big-endian', classicVariant(false, false));
await save('tcp-handshake-nanoseconds', classicVariant(true, true));
await writeFile(resolve(generated, 'tcp-handshake.pcapng'), pcapng());
await writeFile(
  resolve(manifests, 'tcp-handshake-pcapng.json'),
  manifestJson('tcp-handshake-pcapng', 'tcp-handshake.pcapng', pcapng(), [1, 2, 3]),
);
await savePcapng('ipv6-udp', ipv6UdpPcapng(), [1]);
