import { createHash } from 'node:crypto';
import { readdirSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { format } from 'prettier';
import { describe, expect, it } from 'vitest';
import {
  HTTP_BODY_SENTINEL,
  HTTP_HEADER_SENTINEL,
  buildPlaintextHttpPcap,
  buildTlsHandshakePcap,
} from './build-phase2-captures.js';

const fixtureRoot = resolve(import.meta.dirname, '..');
const generatedRoot = resolve(fixtureRoot, 'generated');
const manifestRoot = resolve(fixtureRoot, 'manifests');

const sha256 = (bytes: Uint8Array) => createHash('sha256').update(bytes).digest('hex');

function packetPayloads(bytes: Uint8Array): Uint8Array[] {
  const payloads: Uint8Array[] = [];
  let recordOffset = 24;
  while (recordOffset < bytes.byteLength) {
    const capturedLength = new DataView(bytes.buffer).getUint32(recordOffset + 8, true);
    const frameOffset = recordOffset + 16;
    payloads.push(bytes.slice(frameOffset + 54, frameOffset + capturedLength));
    recordOffset += 16 + capturedLength;
  }
  return payloads;
}

describe('plaintext HTTP and TLS fixtures', () => {
  it('builds stable captures with the reviewed packet counts and hashes', () => {
    const plaintext = buildPlaintextHttpPcap();
    const tls = buildTlsHandshakePcap();

    expect(plaintext).toHaveLength(963);
    expect(tls).toHaveLength(511);
    expect(sha256(plaintext)).toBe(
      '6064857146336cc58a223392be5844e8e89b14e27936732376a964b2e1ec1026',
    );
    expect(sha256(tls)).toBe('3291fd0be48404b4dc03d3d8bd8e146835113816f7e0e7ba83cce39521d7f196');
    expect([...plaintext]).toEqual([
      ...readFileSync(resolve(generatedRoot, 'plaintext-http.pcap')),
    ]);
    expect([...tls]).toEqual([...readFileSync(resolve(generatedRoot, 'tls-handshake.pcap'))]);
  });

  it('keeps manifests formatted, checksummed, licensed, and packet-complete', async () => {
    const cases = [
      { name: 'plaintext-http', bytes: buildPlaintextHttpPcap(), packets: [1, 2, 3, 4, 5, 6, 7] },
      { name: 'tls-handshake', bytes: buildTlsHandshakePcap(), packets: [1, 2, 3, 4, 5] },
    ];
    for (const testCase of cases) {
      const manifestText = readFileSync(resolve(manifestRoot, `${testCase.name}.json`), 'utf8');
      const manifest = JSON.parse(manifestText) as {
        sha256: string;
        byteLength: number;
        license: string;
        packets: number[];
      };
      expect(manifestText).toBe(
        await format(manifestText, {
          parser: 'json',
          printWidth: 100,
          tabWidth: 2,
          useTabs: false,
        }),
      );
      expect(manifest.sha256).toBe(sha256(testCase.bytes));
      expect(manifest.byteLength).toBe(testCase.bytes.byteLength);
      expect(manifest.license).toBe(
        'Original synthetic traffic generated by WireLens; no real network traffic or captured user data.',
      );
      expect(manifest.packets).toEqual(testCase.packets);
    }
  });

  it('does not copy HTTP secret sentinels into fixture metadata', () => {
    const metadataFiles = [
      ...readdirSync(manifestRoot).map((name) => resolve(manifestRoot, name)),
      ...readdirSync(resolve(fixtureRoot, 'expected')).map((name) =>
        resolve(fixtureRoot, 'expected', name),
      ),
      resolve(fixtureRoot, 'README.md'),
    ];
    for (const file of metadataFiles) {
      const metadata = readFileSync(file, 'utf8');
      expect(metadata, file).not.toContain(HTTP_HEADER_SENTINEL);
      expect(metadata, file).not.toContain(HTTP_BODY_SENTINEL);
    }
  });

  it('includes the two distinct HTTP sentinels only in capture payload bytes', () => {
    const bytes = new TextDecoder().decode(buildPlaintextHttpPcap());
    expect(bytes).toContain(HTTP_HEADER_SENTINEL);
    expect(bytes).toContain(HTTP_BODY_SENTINEL);
    expect(HTTP_HEADER_SENTINEL).not.toBe(HTTP_BODY_SENTINEL);
  });

  it('keeps HTTP data in ordered segments and includes valid response bytes', () => {
    const payloads = packetPayloads(buildPlaintextHttpPcap());
    expect(payloads).toHaveLength(7);
    expect(payloads.slice(0, 3).map((payload) => payload.byteLength)).toEqual([0, 0, 0]);
    expect(new TextDecoder().decode(payloads[3])).toMatch(
      /^POST \/search\?term=private&sort=recent HTTP\/1\.1\r\n/u,
    );
    expect(new TextDecoder().decode(payloads[4])).toContain('\r\n\r\n');
    expect(new TextDecoder().decode(payloads[5])).toBe(`{"value":"${HTTP_BODY_SENTINEL}"}`);
    expect(new TextDecoder().decode(payloads[6])).toMatch(/^HTTP\/1\.1 200 OK\r\n/u);
  });

  it('keeps a valid ClientHello and ServerHello record pair on ordered TCP data', () => {
    const payloads = packetPayloads(buildTlsHandshakePcap());
    expect(payloads).toHaveLength(5);
    expect([...payloads[3].slice(0, 5)]).toEqual([0x16, 0x03, 0x01, 0x00, 0x4d]);
    expect([...payloads[3].slice(5, 9)]).toEqual([0x01, 0x00, 0x00, 0x49]);
    expect([...payloads[4].slice(0, 5)]).toEqual([0x16, 0x03, 0x03, 0x00, 0x32]);
    expect([...payloads[4].slice(5, 9)]).toEqual([0x02, 0x00, 0x00, 0x2e]);
    expect([...payloads[3].slice(-9)]).toEqual([
      0x00, 0x2b, 0x00, 0x05, 0x04, 0x03, 0x04, 0x03, 0x03,
    ]);
    expect([...payloads[4].slice(-6)]).toEqual([0x00, 0x2b, 0x00, 0x02, 0x03, 0x04]);
  });
});
